### ISSUE TITLE
[Feature] Add AssemblyScript support

### ISSUE THREAD

**Issue by YiraSan** [ApsarasX/llvm-bindings#11]
Because the main file on npm is a JavaScript file and not esModule, AssemblyScript can't import llvm-bindings

**Comment by ApsarasX** [comment]
Sorry, I don't think this is possible at the moment.

`llvm-bindings` is essentially a Node.js addon that expose the LLVM API through [node-addon-api](https://github.com/nodejs/node-addon-api/).

Assuming that for `llvm-bindings` to support AssemblyScript, all LLVM dynamic libraries must be converted to WASM, which is currently difficult.

In addition, LLVM uses a large number of APIs provided by the operating system, and these APIs cannot find alternatives in the WASI.

**Comment by YiraSan** [comment]
I misspoke, I wanted to say that can be cool to import llvm-bindings from AssemblyScript not llvm-bindings to be WASM lib sorry

**Comment by ApsarasX** [comment]
> I misspoke, I wanted to say that can be cool to import llvm-bindings from AssemblyScript not llvm-bindings to be WASM lib sorry

The two you mentioned are actually the same problem.

`llvm-bindings` needs to call the dynamic link library provided by LLVM, but AssemblyScript currently cannot support this.
