### ISSUE TITLE
[Bug] Command to install in Windows 10 not working

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ApsarasX/llvm-bindings#12]
**Your environment**
- OS version: Windows 10
- Node.js version: N/A
- LLVM version: 13.0.1

**Describe the bug**
I ran this command, after doing the first few steps in the wiki:
```
cmake -Thost=x64 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_INCLUDE_TESTS=OFF ..
CMake Error: The source directory "C:/LLVM" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
I think I need to cd to a specific dir first.

**Expected behavior**
Not CMake error.

**Comment by ApsarasX** [comment]
The reason you are getting error is because you are not in the correct folder.

You should first create a new folder named `build` under the source directory.

Then, enter the `build` directory and execute

```shell
cmake -Thost=x64 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_INCLUDE_TESTS=OFF ..
```

**Comment by ChocolateLoverRaj** [comment]
@ApsarasX Actually I did the first step wrong. Instead of downloading the file the wiki says I cloned the llvm git repo. I will try with the tar.xz file, which has cmake lists.

**Comment by ApsarasX** [comment]
I see, you cloned [llvm-project](https://github.com/llvm/llvm-project), which is a monorepo that contains llvm and other stuff.

Actually, the `LLVM` I'm referring to is https://github.com/llvm/llvm-project/tree/main/llvm, which is  just a subfolder of [llvm-project](https://github.com/llvm/llvm-project).

**Comment by ChocolateLoverRaj** [comment]
I followed the steps and it works 👍
