### ISSUE TITLE
postinstall - no member named 'getTypeByName' in 'llvm::Module'

### ISSUE THREAD

**Issue by bconnorwhite** [ApsarasX/llvm-bindings#2]
postinstall gives this error:
```
src/IR/Module.cpp:101:38: error: no member named 'getTypeByName' in 'llvm::Module'
    llvm::StructType *type = module->getTypeByName(name);
                             ~~~~~~  ^
```
Commenting out lines 101-104 at least allows postinstall to complete

**Comment by ApsarasX** [comment]
Sorry, I haven't reproduced this problem on my computer. It seems that the problem is caused by the version difference of llvm. I am using llvm-11. What is your llvm version?

**Comment by bconnorwhite** [comment]
Thanks, downgrading to v11 worked, brew is installing 12 by default

**Comment by bconnorwhite** [comment]
Ah, I noticed your install instructions for Ubuntu specify llvm-11, could be helpful to add the version for brew as well

**Comment by ApsarasX** [comment]
I will add support for llvm-12 soon.

**Comment by ApsarasX** [comment]
I have switched the version of llvm to 12, but llvm-11 is no longer supported. 
Please carefully review the content about [version compatibility](https://github.com/ApsarasX/llvm-bindings#note)
