### ISSUE TITLE
[Feature] GlobalVariable::setInitializer support

### ISSUE THREAD

**Issue by dvoytenko** [ApsarasX/llvm-bindings#20]
[GlobalVariable::setInitializer](https://llvm.org/doxygen/classllvm_1_1GlobalVariable.html#a095f8f031d99ce3c0b25478713293dea) is very helpful when the global constants need to be predeclared, but can only be computed later.

**Comment by ApsarasX** [comment]
well, I will add this method this week.

**Comment by dvoytenko** [comment]
Thank you!

**Comment by ApsarasX** [comment]
I have added this method in v0.4.2.
