### ISSUE TITLE
[Bug] Allot of the [Type].is* methods (and others) throwing exceptions

### ISSUE THREAD

**Issue by CaseyAllen** [ApsarasX/llvm-bindings#22]
**Your environment**
- OS version: Arch x86_64(Linux** 5.15.55-1-lts)
- Node.js version: v18.6.0
- LLVM version: 14.0.6

**Describe the bug**

Many of the methods on type instances are throwing runtime TypeErrors `TypeError: Illegal invocation`
sometimes they work but the majority of the time they dont

**Expected behavior**

they should not throw errors, and instead respond with the appropriate value

**Comment by ApsarasX** [comment]
Please refer to #1.

Please tell me all the methods you want to call like above, and I will add them manually.
